### ISSUE TITLE
assertions are wrong because of wrong html output

### ISSUE THREAD

**Issue by Zae** [nunomaduro/laravel-mojito#3]
Hi,

It seems that DomCrawler changes my HTML which makes my tests fail.

Lets say the output from my view is:
~~~
WIDGETBEFBEFOREArchivesAFTER
<ul></ul>
WIDGETAFT
~~~

And I test like this:

~~~
static::assertView('view)
            ->contains('BEFORE')
            ->contains('AFTER')
            ->contains('WIDGETBEF');
            ->contains('WIDGETAFT');
~~~

This fails because mojito thinks the output of the view is:

~~~
<p>WIDGETBEFBEFOREArchivesAFTER</p>
~~~

This is definitely not the output of the view, but this is probably what DomCrawler makes of it when it imports the HTML.

**Comment by nunomaduro** [comment]
Can you try to debug this to track this specific line of this problem ?

**Comment by Zae** [comment]
Hi Nuno,

I've added a testcase in my PR, you can see the failure in travis.

**Comment by fdalcin** [comment]
This is happening because of how the crawler parses the content.

It parses the content to something like this:

```html
<body>
    <p>WIDGETBEFBEFOREArchivesAFTER</p>
    <ul></ul>
    WIDGETAFT
</body>
```

Then the line below ends up with only the following ```WIDGETBEFBEFOREArchivesAFTER``` which is not what you want.
https://github.com/nunomaduro/laravel-mojito/blob/5185a54d65caf79623cc33317e511970a5178fbc/src/ViewAssertion.php#L32

Wrapping your content within ```div``` tag would work as expected.
